### ISSUE TITLE
Task: Design Higher Quality Logo

### ISSUE THREAD

**Issue by alexmdodge** [alexmdodge/github-diff-explorer#19]
It can be better.

**Comment by andeladenaro** [comment]
Hi. I'm Andela Denaro, I would like to contribute new logo for Github Diff Explorer. Do you have any requirement to the new logo design?

**Comment by alexmdodge** [comment]
@andeladenaro Hi! That would be fantastic! No strict requirements, really anything is better than what I have right now. Some ideas for the process,

* Should relate to folder exploring, searching, along those lines
* Logo should be simplistic and visible, it's more of an icon so having it visible at small sizes is important
* For the final product include the full size (at least 128x128 pixels)
* You can email me the resulting logo or submit a pull request and just include it in the [images directory](https://github.com/alexmdodge/github-diff-explorer/tree/master/extension/images)

**Comment by andeladenaro** [comment]
Hi, here's my ideas. What do you think?

![github diff explorer idea](https://user-images.githubusercontent.com/35057858/38404853-0d38eb78-3997-11e8-91e7-92874ff44c22.png)

**Comment by alexmdodge** [comment]
@andeladenaro Wow, these are incredible! I'm impressed 👍 

I think the top one would be a great banner icon for the project, the middle is a fantastic icon, and the file black and white I can include right in the plugin window itself.

I'll make sure to give you extended credit, both in the README, and the extension popup. As I mentioned feel free to include these through your own pull request or you can send them to me and I'll add them! Do you have any other information you wish me to include in the project to give you proper reference?

**Comment by andeladenaro** [comment]
Hi! Thanks for the appreciation. I think that's enough for me. 

You can download all files [here](https://drive.google.com/open?id=1VldCen8Tn7Yxu_zbGsQp0am-ujBQMbU_). There are banner, icon, and logotype included. I will try to create a pull request after this.

Feel free to ask and let me know if you need another file size.

**Comment by andeladenaro** [comment]
Hi Alex, did the "o" letter in the phrase "Explorer" with search icon bother you? Do you think that looks like Q than O? If you do, I can change to what you thought. 
Thank you.
