### ISSUE TITLE
Improvement: Enable explorer column to be resizable

### ISSUE THREAD

**Issue by michaelcunningham19** [alexmdodge/github-diff-explorer#27]
Allowing the explorer column to be resizable by the user will cover any cases where a pull request is becoming hard to read with smaller-width displays

Thoughts on this @alexmdodge  ?

(Added for tracking on the issue)
- [x] Make explorer resizeable
- [x] Add buttons to quickly collapse and expand the width of the explorer

**Comment by alexmdodge** [comment]
@michaelcunningham19 I like it! I think there are a couple of things I would like to implement to help with explorer navigation.

- [ ] Make explorer resizeable
- [ ] Add buttons to quickly collapse and expand the width of the explorer
- [ ] Add buttons to collapse all folders as well as expand all
