### ISSUE TITLE
Enhancement: Support Firefox

### ISSUE THREAD

**Issue by mtfum** [alexmdodge/github-diff-explorer#64]
Hi! Thank you for great extension!
I want to use on Firefox, do you have any plans?

**Comment by alexmdodge** [comment]
Definitely have thought about it! Given how simple the extension is, and that it largely just acts on DOM elements for the pages, it would probably be relatively simple. I'll look into it as I consider the next couple releases.

**Comment by mtfum** [comment]
Sounds nice!
I'm looking forwad to it.

**Comment by alexmdodge** [comment]
Noting that extension support for Firefox was added in #67. This build should be available on the Add-Ons store within the next week. Will post the link here when it is.

**Comment by alexmdodge** [comment]
@mtfum Now available on Firefox:
https://addons.mozilla.org/en-GB/firefox/addon/github-diff-explorer/

**Comment by mtfum** [comment]
@alexmdodge Great 🎉 Thank you!
